cloudformation:
  cli:
    validate-cfn: true
    stack-action: deploy
  options:
    cfn-stack-name: bitops-stack-test
    cfn-files:
      template-file: template.yaml
      parameters:
        template-param-flag: true
        template-param-file: parameters.json
