helm:
  cli:
    namespace: bitops
    timeout: 60s
    set:
    - "key1=value1"
    - "key2=value2"
    debug: false
    atomic: true
  options:
    release-name: bitops-release
    k8s:
      fetch:
        kubeconfig: true
        cluster-name: bitops-test-opscruise-ekscluster
